# Generated by Django 3.2.4 on 2023-07-03 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramognee', '0002_auto_20230703_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='reporter_name',
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
